# Starship Tokyo Night Preset
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:#7aa2f7)\
$os\
$username\
[](bg:#3b4261 fg:#7aa2f7)\
$directory\
[](fg:#3b4261 bg:#24283b)\
$git_branch\
$git_status\
[](fg:#24283b bg:#1f2335)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#1f2335 bg:#16161e)\
$time\
[ ](fg:#16161e)\
"""

# Disable the blank line at the start of the prompt
add_newline = true

[os]
disabled = false
style = "bg:#7aa2f7 fg:#16161e"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐚"
Mint = "󰣭"
Macos = "󰀵"
Linux = "󰌽"
NixOS = ""
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = "󰄖"
Arch = "󰣇"
Artix = "󰣍"
EndeavourOS = ""
Debian = "󰣚"

[username]
show_always = true
style_user = "bg:#7aa2f7 fg:#16161e"
style_root = "bg:#7aa2f7 fg:#16161e"
format = '[ $user ]($style)'

[directory]
style = "bg:#3b4261 fg:#7aa2f7"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = "󰇚 "
"Music" = "󰝚 "
"Pictures" = "󰙅 "

[git_branch]
symbol = ""
style = "bg:#24283b fg:#7aa2f7"
format = '[[ $symbol $branch ]($style)]($style)'

[git_status]
style = "bg:#24283b fg:#7aa2f7"
format = '[[($all_status$ahead_behind )]($style)]($style)'

[nodejs]
symbol = ""
style = "bg:#1f2335 fg:#7aa2f7"
format = '[[ $symbol ($version) ]($style)]($style)'

[rust]
symbol = ""
style = "bg:#1f2335 fg:#7aa2f7"
format = '[[ $symbol ($version) ]($style)]($style)'

[golang]
symbol = ""
style = "bg:#1f2335 fg:#7aa2f7"
format = '[[ $symbol ($version) ]($style)]($style)'

[php]
symbol = ""
style = "bg:#1f2335 fg:#7aa2f7"
format = '[[ $symbol ($version) ]($style)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#16161e fg:#7aa2f7"
format = '[[ 󱑒 $time ]($style)]($style)'
